# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require(File.join(File.dirname(__FILE__), 'config', 'boot'))

require 'rake'
require 'rake/testtask'
require 'rake/rdoctask'

require 'tasks/rails'




namespace :test_unit do
  desc "runs the test::unit based tests in webrat mode"
  task :rails do
    ENV['WEBRAT_INTEGRATION_MODE'] = 'rails'
    Rake::Task['test:integration'].execute
  end

  desc "runs the test::unit based tests in selenium mode"
  task :selenium do
    ENV['WEBRAT_INTEGRATION_MODE'] = 'selenium'
    Rake::Task['test:integration'].execute
  end

  desc "runs the test::unit based tests in webdriver mode"
  task :webdriver do
    ENV['WEBRAT_INTEGRATION_MODE'] = 'webdriver'
    Rake::Task['test:integration'].execute
  end

  desc "run all selenium, webdriver and rails mode Test::Unit suites"
  task :all => [:rails, :selenium, :webdriver]
end
